import com.tax.salary.entity.SalaryTax;

rule "Calculate Salary Tax - 2.5%"
when
    salaryTax: SalaryTax(yearlySalary > 600000 && yearlySalary <= 1200000)
then
    salaryTax.setSalaryTaxPercentage(2.5);
    salaryTax.setTaxableAmount(salaryTax.getYearlySalary() - 600000);
end

rule "Calculate Salary Tax - 12.5% "
when
    salaryTax: SalaryTax(yearlySalary > 1200000 && yearlySalary <= 2400000)
then
    salaryTax.setSalaryTaxPercentage(12.5);
    salaryTax.setTaxableAmount(salaryTax.getYearlySalary() - 1200000);
    salaryTax.setFixedAmount(15000);
end

rule "Calculate Salary Tax - 20% "
when
    salaryTax: SalaryTax(yearlySalary > 2400000 && yearlySalary <= 3600000)
then
    salaryTax.setSalaryTaxPercentage(20);
    salaryTax.setTaxableAmount(salaryTax.getYearlySalary() - 2400000);
    salaryTax.setFixedAmount(165000);
end

rule "Calculate Salary Tax - 25% "
when
    salaryTax: SalaryTax(yearlySalary > 3600000 && yearlySalary <= 6000000)
then
    salaryTax.setSalaryTaxPercentage(25);
    salaryTax.setTaxableAmount(salaryTax.getYearlySalary() - 3600000);
    salaryTax.setFixedAmount(405000);
end

rule "Calculate Salary Tax - 32.5% "
when
    salaryTax: SalaryTax(yearlySalary > 6000000 && yearlySalary <= 12000000)
then
    salaryTax.setSalaryTaxPercentage(32.5);
    salaryTax.setTaxableAmount(salaryTax.getYearlySalary() - 6000000);
    salaryTax.setFixedAmount(1005000);
end

rule "Calculate Salary Tax - 35% "
when
    salaryTax: SalaryTax(yearlySalary > 12000000 && yearlySalary <= 999999999)
then
    salaryTax.setSalaryTaxPercentage(35);
    salaryTax.setTaxableAmount(salaryTax.getYearlySalary() - 12000000);
    salaryTax.setFixedAmount(2955000);
end


